var arrayData = [
	"A lua",
	"Abacate",
	"Abacaxi",
	"Abajur",
	"Abelha",
	"Abelha",
	"Abelha",
	"Abóbora",
	"Abrigo de jardim",
	"Abrigo",
	"Abutre",
	"Academia",
	"Acampamento",
	"Acampamento",
	"Ação de graças",
	"Aceno",
	"Achocolatado",
	"Acompanhar",
	"Açougueiro",
	"Açúcar",
	"Advogado",
	"Aeroporto",
	"Afundar",
	"Agricultor",
	"Agricultura",
	"Água",
	"Águia",
	"Agulha",
	"Aladim",
	"Alarme",
	"Alce",
	"Aldeão",
	"Alface",
	"Alfinete",
	"Algas marinhas",
	"Algemas",
	"Algodão doce",
	"Alicates",
	"Alimentador de pássaros",
	"Almoço",
	"Almofada",
	"Almôndega",
	"Alojamento de esqui",
	"Alpendre",
	"Alto",
	"Alvo",
	"Ambiente",
	"Ambulância",
	"Amendoim",
	"América",
	"Ampulheta",
	"Anão",
	"Ancinho",
	"Âncora",
	"Andaime",
	"Andar de bicicleta",
	"Andar de",
	"Andróide",
	"Anéis de Ginástica",
	"Anel de Boxe",
	"Anel de cebola",
	"Anel de diamante",
	"Anel de noivado",
	"Anel de ouro",
	"Anel",
	"Animais",
	"Animal",
	"Aniversário",
	"Anjo",
	"Apagador",
	"Aperto de mão",
	"Aplaudir",
	"Apocalipse Zumbi",
	"Apocalipse",
	"Apresentação",
	"Aquário",
	"Aquário",
	"Aquário",
	"Arame",
	"Aranha",
	"Arbusto de rosas",
	"Arbusto",
	"Arco de cabelo",
	"Arco e flecha",
	"Arco-íris",
	"Arco",
	"Área de camping",
	"Areia movediça",
	"Aréola",
	"Argila",
	"Aríete",
	"Armadilha",
	"Armaduras",
	"Armário",
	"Armário",
	"Armazenar",
	"Arqueiro",
	"Arraia",
	"arranha-céu",
	"Arroz",
	"Arte de pixel",
	"Arte Moderna",
	"Arte",
	"Artista",
	"Árvore de maçã",
	"Árvore de Natal",
	"Árvore morta",
	"Árvore",
	"ASA delta",
	"ASA delta",
	"Asas",
	"Aspersor",
	"Assento",
	"Assistir",
	"Assobiar",
	"Assustado",
	"Astronauta",
	"Atadura",
	"Atirador de elite",
	"Atmosfera",
	"Atum",
	"Aula",
	"Austrália",
	"Auto-retrato",
	"Autoestrada",
	"Automóvel",
	"Avestruz",
	"Avião Afundado",
	"Avião de papel",
	"Avião",
	"Backflip",
	"Bacon",
	"Badminton",
	"Baga",
	"Bagagem",
	"Bagas",
	"Baguete",
	"Baía",
	"Bala de canhão",
	"Bala",
	"Balanço de pneu",
	"Balanço",
	"Balão de aguá",
	"Balão de ar quente",
	"Balão",
	"Balde de água",
	"Balde de gelo",
	"Balde de Lava",
	"Balde de tinta",
	"Balde",
	"Baleia",
	"Balões",
	"Balsa",
	"Bambolê",
	"Bambu",
	"Banana",
	"Banco",
	"Banco",
	"Banda de rock",
	"Banda",
	"Bandeira alemã",
	"Bandeira francesa",
	"Bandeira",
	"Bandeiras",
	"Bandido",
	"Banheira",
	"Banheira",
	"Banheiro",
	"Banheiro",
	"Banho de espuma",
	"Banho de Pássaro",
	"Banho",
	"Banho",
	"Banjo",
	"Baqueta",
	"Baquetas",
	"Bar",
	"Baralho de cartas",
	"Barata",
	"Barba",
	"Barbear",
	"Barco a remo",
	"Barco a vela",
	"Barco a vela",
	"Barco",
	"Barra de chocolate",
	"Barraca de limonada",
	"Barraca",
	"Barraca",
	"Barreira",
	"Barril",
	"Basilisco",
	"Basquetebol",
	"Basquetebol",
	"Bastão",
	"Batata frita",
	"Batata",
	"Batatas fritas",
	"Batatas",
	"Bateria",
	"Bateria",
	"Batido",
	"Batom",
	"Baú de tesouro",
	"Bebê",
	"Bebida",
	"Beijo",
	"Beisebol",
	"Beliche",
	"Bem",
	"Bengala de doce",
	"Bengala",
	"Berço",
	"Beringela",
	"Besouro",
	"Besta",
	"Biblioteca",
	"Bibliotecário",
	"Bicho de estimação",
	"Bicicleta",
	"Bicicleta",
	"Bife",
	"Bigode",
	"Bigorna",
	"Bilhete",
	"Bingo",
	"Binóculos",
	"Biologia",
	"Biscoito da sorte",
	"biscoito de natal",
	"Biscoito",
	"Bloco de anotações",
	"Blocos",
	"Bloqueio",
	"Bob Esponja",
	"Bobagem",
	"Bobsledding",
	"Boca",
	"Bola de boliche",
	"Bola de chiclete",
	"Bola de cristal",
	"Bola de discoteca",
	"Bola de futebol",
	"Bola de neve",
	"Bola de praia",
	"Bola de tênis",
	"Bola fogo",
	"Bolacha com pepitas de chocolate",
	"Bolacha",
	"Bolha",
	"Bolhas",
	"Boliche",
	"Bolinho",
	"Bolo de aniversário",
	"Bolo de casamento",
	"Bolo de chocolate",
	"Bolo de queijo",
	"Bolo",
	"Bolsa de compras",
	"Bolsa",
	"Bolsa",
	"Bolsa",
	"Bombear",
	"Bombear",
	"Bombeiro",
	"Boné",
	"Boneca",
	"Boneco de neve",
	"Borboleta",
	"Borracha",
	"Botão",
	"Botas de escalada",
	"Botas",
	"Boxe",
	"Braço",
	"Brilhante",
	"Brinco",
	"Brinde",
	"Brinquedo",
	"Brócolis",
	"Bruxa",
	"Bufê",
	"Bule",
	"Bulldozer",
	"Bumerangue",
	"Buraco negro",
	"Buraco",
	"Burro",
	"Bússola",
	"buzina de ar",
	"Buzina",
	"Cabana de toras",
	"Cabana",
	"Cabana",
	"Cabeça",
	"Cabeleireiro",
	"Cabelo",
	"Cabide",
	"Cabine de DJ",
	"Cabine telefônica",
	"Cabine",
	"Cabo-de-guerra",
	"Cabo",
	"Cabra",
	"Caçador",
	"Cachoeira",
	"Cachorro de milho",
	"Cachorro Passeando",
	"Cachorro-quente",
	"Cachorro",
	"Cacto",
	"cadarços de sapato",
	"Cadeado",
	"Cadeia",
	"Cadeira de balanço",
	"Cadeira de jogos",
	"Cadeira",
	"Cadeiras",
	"Cães",
	"Café da manhã na cama",
	"Café da manhã",
	"Café",
	"Caiaque",
	"Caixa de areia",
	"Caixa de chocolate",
	"Caixa de chocolates",
	"Caixa de compostagem",
	"Caixa de correio",
	"Caixa de explosão",
	"Caixa de papelão",
	"Caixa mistério",
	"Caixa registradora",
	"Caixa",
	"Caixa",
	"Caixa",
	"Caixão",
	"Caixas de som",
	"Calça",
	"Calçada",
	"Calculadora",
	"Caldeirão",
	"Calendário do Advento",
	"Calendário",
	"Cálice",
	"Cama de dossel",
	"Cama",
	"Camaleão",
	"Camelo",
	"Câmera de segurança",
	"Câmera de vídeo",
	"Câmera",
	"Caminhão de lixo",
	"Caminhão de reboque",
	"Caminhão",
	"Caminho",
	"Camisa",
	"Camiseta",
	"Campo de beisebol",
	"Campo de futebol",
	"Campo de golfe",
	"Campo",
	"Camuflar",
	"Cana de pesca",
	"Canadá",
	"Canal",
	"Canção",
	"Caneca",
	"Caneta",
	"Canguru",
	"Canhão TNT",
	"Canhão",
	"Canil",
	"Cano",
	"Canoa",
	"Canteiro de flores",
	"Canto",
	"Cantor",
	"Cantoria",
	"Canudo",
	"Cão de guarda",
	"Capa de celular",
	"Capa de chuva",
	"Capa",
	"Capa",
	"Capacete",
	"Caranguejo",
	"Caravana",
	"Careca",
	"Caribe",
	"Carimbo",
	"Carnaval",
	"Carne bovina",
	"Carolando",
	"Carpinteiro",
	"Carranca",
	"Carregador de celular",
	"Carregador de telefone",
	"Carregador",
	"Carreta",
	"Carrinho de compras",
	"Carrinho de golfe",
	"Carrinho",
	"Carrinho",
	"Carro de corrida",
	"carro de polícia",
	"Carro de Polícia",
	"Carro",
	"Carros de choque",
	"Carta",
	"Cartão de crédito",
	"Cartão de Natal",
	"Cartão postal",
	"Cartão",
	"Cartas de jogar",
	"Carteira",
	"Carteiro",
	"Cartões",
	"Cartola",
	"Carvão",
	"Casa Assombrada",
	"Casa Assustadora",
	"Casa da bruxa",
	"Casa de boneca",
	"Casa de diversão",
	"Casa de fazenda",
	"Casa de Pão de Gengibre",
	"Casa de Sujeira",
	"Casa Futurista",
	"Casa Medieval",
	"Casa moderna",
	"Casa na árvore",
	"Casa",
	"Casaco",
	"Casamento",
	"Casca de banana",
	"Cascalho",
	"Cassete",
	"Castanha",
	"Castelo de Areia",
	"Castelo de Areia",
	"Castelo de Gelo",
	"Castelo inflável",
	"Castelo",
	"Castor",
	"Casulo",
	"Catacumba",
	"Catapulta",
	"Cauda",
	"Cavaleiro",
	"Cavalo de corrida",
	"Cavalo marinho",
	"Cavalo",
	"Caverna",
	"Ceifador",
	"Cela de prisão",
	"Celeiro",
	"Célula",
	"Celular",
	"Cemitério",
	"Cena do filme",
	"Cenoura",
	"Cenouras",
	"Centauro",
	"Cerca",
	"Cereal",
	"Cérebro",
	"Cereja",
	"Cerejas",
	"Cervo",
	"Cesta de basquete",
	"Cesta de Lavagem",
	"Cesta",
	"Cesto de frutas",
	"Cesto de lixo",
	"Cesto de roupa suja",
	"Céu",
	"Chá e Biscoitos",
	"Chá",
	"Chaleira",
	"Chama",
	"Chama",
	"Chaminé",
	"Chão",
	"Chapéu de caubói",
	"Chapéu de Chef",
	"Chapéu de Feiticeiro",
	"Chapéu de festa",
	"Chapéu Mágico",
	"Chapéu Pirata",
	"Chapéu",
	"Chave de fenda",
	"Chave inglesa",
	"Chave inglesa",
	"Chave",
	"Chaves",
	"Chefe de cozinha",
	"Cheiro",
	"Chiclete",
	"Chihuahua",
	"China",
	"Chinelos",
	"Chocolate quente",
	"Chocolate",
	"Chorar",
	"Churrasco",
	"Churrasqueira",
	"Chuva",
	"Ciclo",
	"Ciclone",
	"Ciclope",
	"Ciência",
	"Cientista maluco",
	"Cientista",
	"Cinema",
	"Cinema",
	"Cinto",
	"Cír",
	"Circo",
	"Círculo",
	"Cirurgia",
	"Cisne",
	"Clima",
	"Clipe de papel",
	"Clube de Golf",
	"Coala",
	"Cobertor",
	"Cobertura",
	"Cobra",
	"Coco",
	"Código de barras",
	"Coelhinho da Páscoa",
	"Coelhinho",
	"Coelho",
	"Cofre",
	"Cofrinho",
	"Cogumelo",
	"Cola",
	"Colar",
	"Colchão",
	"Coleira",
	"Colete salva-vidas",
	"Colher",
	"Colina",
	"Colméia",
	"Coluna",
	"Comédia",
	"Comemoro",
	"Comendo",
	"Cometa",
	"Comida rápida",
	"Comida",
	"Competição de Comer",
	"Competição de dança",
	"Comprar",
	"Compras",
	"Computador portátil",
	"Computador",
	"Concha",
	"Concorrente",
	"Console de jogos",
	"Construção da cidade",
	"Construção",
	"Construir batalha",
	"Construtor",
	"Conto de fadas",
	"Controlador de jogos",
	"Controlador",
	"Controle de video game",
	"Controle remoto",
	"Controle remoto",
	"Controlo remoto",
	"Copo de água",
	"Copo de leite",
	"Copos",
	"Coração",
	"corda bamba",
	"Corda",
	"Corda",
	"Cordeiro",
	"Cornucópia",
	"Coroa",
	"Corredor",
	"Corredor",
	"Correia transportadora",
	"Correios",
	"Correndo",
	"Corrente",
	"Correspondência",
	"Corrida de cavalo",
	"Corrida",
	"Corrida",
	"Corrida",
	"Cortador de grama",
	"Corte de cabelo",
	"Cortina",
	"Cortinas",
	"Coruja",
	"Corvo",
	"Cotovelo",
	"Couro",
	"Couve-flor",
	"Cova",
	"Covinhas",
	"Cowbell",
	"Cozimento",
	"Cozinha",
	"Cozinhar",
	"Crachá",
	"Crânio",
	"Cratera",
	"Criança",
	"Criminoso",
	"Cristal",
	"Crocodilo",
	"Cronômetro",
	"Cruzeiro",
	"Cruzeiro",
	"Cubo de gelo",
	"Cubo de magma",
	"Cubo de Rubik",
	"Cubo Quebra-cabeça",
	"Cubo",
	"Culinária",
	"Curativo",
	"Curto",
	"Dab",
	"Dados",
	"Dança",
	"Dançando",
	"Dançarino",
	"Dardo",
	"Data",
	"De cabeça para baixo",
	"Declive",
	"Decoração",
	"Decorações",
	"Dedão",
	"Dedo",
	"Dedos de galinha",
	"Dedos do pé",
	"Delegacia de polícia",
	"Demônio",
	"Dentaduras",
	"Dente",
	"Dentes",
	"Dentista",
	"Desaparecer",
	"Desdentado",
	"Desejando bem",
	"Desenho animado",
	"Desenho",
	"Desentupidor",
	"Deserto",
	"Deslizar",
	"Desodorante",
	"Despertador",
	"Detector de metal",
	"Dia das Bruxas",
	"Dia",
	"Diabo",
	"Diamante",
	"Dinamite",
	"Dinheiro",
	"Dinheiro",
	"Dinossauro",
	"Dirigível",
	"Dirigível",
	"Disco",
	"Discoteca",
	"Distintivo",
	"Distribuidor",
	"Ditador",
	"Doce de açúcar",
	"Doce",
	"Dólar",
	"Dominó",
	"Dormindo",
	"Dormir",
	"Doutor",
	"Dragão Ender",
	"Dragão",
	"Drive-through",
	"Duende",
	"Duende",
	"Duende",
	"DVD",
	"Eclipse",
	"Eclosão de Ovos",
	"Egito",
	"Eixo de minas",
	"Elástico de borracha",
	"Elástico de cabelo",
	"Elástico",
	"Elefante",
	"Eletricidade",
	"Elevador",
	"Elmo",
	"Embaixo da agua",
	"Emoji",
	"Encantar",
	"Enchente",
	"Enderman",
	"Energia",
	"Enfermeira",
	"Engarrafamento",
	"Engrenagem",
	"Enguia",
	"Entrada de automóveis",
	"Envelope",
	"Enviando mensagens de texto",
	"Enviar",
	"Equestre",
	"Erro",
	"Erupção vulcânica",
	"Ervilha",
	"Escada rolante",
	"Escada",
	"Escada",
	"Escadaria",
	"Escadaria",
	"Escadinha",
	"Escala",
	"Escalada",
	"Escalando",
	"Escola",
	"Escolta",
	"Esconde-esconde",
	"Escorpião",
	"Escova de cabelo",
	"Escova de cabelo",
	"Escova de dente",
	"Escovar",
	"Escrita",
	"Escritório",
	"Escudo",
	"Esfera",
	"Esfregar",
	"Esgoto",
	"Esgrima",
	"Esmalte",
	"Esmeralda",
	"Espaço",
	"Espada",
	"Espaguete",
	"Espantalho",
	"Espelho",
	"Espião",
	"Esponja",
	"Esportes",
	"Esportes",
	"Espreguiçadeira",
	"Esqueleto",
	"Esqui aquático",
	"Esqui",
	"Esquiar",
	"Esquilo",
	"Estábulos",
	"Estação de trem",
	"Estacionamento",
	"Estacionamento",
	"Estádio",
	"Estágio",
	"Estante de livros",
	"Estante",
	"Estante",
	"Estátua",
	"Esteira",
	"Estéreo",
	"Estojo de lápis",
	"Estrada de ferro",
	"Estrada de tijolos amarelos",
	"Estrada",
	"Estrangeiro",
	"Estrela do Mar",
	"Estrela",
	"Estrutura de escalada",
	"Estufa",
	"Europa",
	"Exame",
	"Exercício",
	"Exército",
	"Experimentar",
	"Explosão",
	"Extintor de incêndio",
	"Fã",
	"Fábrica de brinquedos",
	"Fábrica de Chocolate",
	"Fábrica",
	"Faca",
	"Face",
	"Fada dos Dentes",
	"Fada",
	"Faixa de pedestre",
	"Família",
	"Fang",
	"Fantasma",
	"Fantoche",
	"Faraó",
	"Farol",
	"Fatia de pão",
	"Favo de mel",
	"Fazenda",
	"Feijão",
	"Feijões",
	"Feixe de equilíbrio",
	"Feliz",
	"Fénix",
	"Feno",
	"Feriado",
	"Ferramentas",
	"Ferro",
	"Festa de aniversário",
	"Festa de Jardim",
	"Festa na praia",
	"Festa Popper",
	"Festa",
	"Festival",
	"Fez",
	"Fidget Spinner",
	"Filhote de cachorro",
	"Filial",
	"Filme",
	"Fin",
	"Fita",
	"Fita",
	"Flamingo",
	"Flauta",
	"Flip telefone",
	"Floco de neve",
	"Flores",
	"Floresta Nevada",
	"Floresta",
	"Fogão",
	"Fogo",
	"Fogos de artifício",
	"Fogueira",
	"Foguete",
	"Foguete",
	"Foguete",
	"Foice",
	"Folha",
	"Folha",
	"Folhas",
	"Fone de ouvido",
	"Fones de ouvido",
	"Fonte",
	"Forcado",
	"Formas",
	"Formiga",
	"Forno",
	"Forno",
	"Forno",
	"Fortaleza",
	"Forte",
	"Fóssil",
	"Fosso",
	"Foto",
	"Fotografia",
	"Fotógrafo",
	"Frango",
	"Frankenstein",
	"Frigideira",
	"Frigideira",
	"Frigorífico",
	"Frisbee",
	"Fronha",
	"Fronteira",
	"Fruta",
	"Frutos do mar",
	"Fumaça",
	"Fumar",
	"Fundição",
	"Furacão",
	"Furão",
	"Furar",
	"Furgão",
	"Futebol americano",
	"Futebol",
	"Futebol",
	"Gabinete",
	"Gafanhoto",
	"Gaiola",
	"Gaivota",
	"Galáxia",
	"galerias",
	"Galho",
	"Galinha",
	"Gancho de luta",
	"Gancho",
	"Gangorra",
	"Ganso",
	"Garagem",
	"Garfo",
	"Garota",
	"Garoto",
	"Garra",
	"Garrafa de agua",
	"Garrafa",
	"Gatinho",
	"Gato",
	"Gêiser",
	"Geladeira",
	"Gelado",
	"Geléia",
	"Gênio",
	"Ghast",
	"Gigante",
	"Ginasta",
	"Girafa",
	"Girassol",
	"GIS de cera",
	"Giz",
	"Globo de neve",
	"Globo",
	"Gnomo",
	"Godzilla",
	"Goleiro",
	"Golem",
	"Golfe",
	"Golfinho",
	"Gordo",
	"Gorila",
	"Gorro",
	"Gota de chuva",
	"Governante",
	"Grã Bretanha",
	"Graduação",
	"Gráfico",
	"Granada",
	"Grande Ben",
	"Grande Canyon",
	"Gravata borboleta",
	"Gravata borboleta",
	"Gravata",
	"Grilo",
	"Grudar",
	"Guarda-chuva",
	"Guarda-roupa",
	"Guardanapo",
	"Guardião",
	"Guaxinim",
	"Guerra das Estrelas",
	"guerra de bolas de neve",
	"Guerreiro",
	"Guindaste",
	"Guitarra",
	"Haltere",
	"Hamburger",
	"Hambúrguer",
	"Hamster",
	"Harmônica",
	"Harpa",
	"Harry Potter",
	"Hélice",
	"Helicóptero",
	"Heliponto",
	"Heptágono",
	"Herói",
	"Hexágono",
	"Hidromassagem",
	"Hipixel",
	"Hipnotizar",
	"Hipopótamo",
	"História de brinquedos",
	"História em quadrinhos",
	"Homem Aranha",
	"Homem de Ferro",
	"Homem Morcego",
	"Homem Porco",
	"Homem-biscoito",
	"Hóquei",
	"Hora de dormir",
	"Horta",
	"Hospital",
	"Hotel",
	"Iate",
	"Iceberg",
	"Icicle",
	"Iglu",
	"Igreja",
	"Ilha deserta",
	"Ilha flutuante",
	"Ilha",
	"Impressora",
	"Indiana Jones",
	"Inferior",
	"Inflamação",
	"Inglaterra",
	"Inseto",
	"Instrumento",
	"Interruptor",
	"Invasores do espaço",
	"Inventar",
	"Inverno",
	"Iogurte",
	"Jacuzzi",
	"Jaguatirica",
	"Janela",
	"Jangada",
	"Jantar",
	"Japão",
	"Jaqueta",
	"Jardim zoológico",
	"Jardim",
	"Jardinagem",
	"jarra",
	"Jato de combate",
	"Jato-esqui",
	"Jaula",
	"Jeans",
	"Joaninha",
	"Joaninha",
	"Joelho",
	"Jogo da velha",
	"Jogo de arcade",
	"Jogo de tabuleiro",
	"Jogo",
	"Jogos de cartas",
	"Jogos de console",
	"Jogos Vorazes",
	"Jóia",
	"Jóias",
	"Jóquei de Frango",
	"Jornal",
	"Judo",
	"Jujubas",
	"Julgamento",
	"Justo",
	"Karatê",
	"Katana",
	"Ketchup",
	"Ketchup",
	"Lã",
	"Lã",
	"Lábios",
	"Labirinto",
	"Laboratório",
	"Laca para cabelo",
	"Lacaio",
	"Laço",
	"Ladrão",
	"Lagarta",
	"Lagarto",
	"Lago",
	"Lago",
	"Lagosta",
	"Lágrimas",
	"Lama",
	"Lambreta",
	"lâminas de rolo",
	"Lâmpada de rua",
	"Lâmpada elétrica",
	"Lâmpada Gênio",
	"Lâmpada",
	"Lança",
	"Lançador de foguetes",
	"Lancha",
	"Lanterna",
	"Lanterna",
	"Lápide",
	"Lápis de cor",
	"Lápis",
	"Lar",
	"Laranja",
	"Lareira",
	"Lasca",
	"Laser",
	"Lata de lixo",
	"Lata de refrigerante",
	"Lata",
	"Latim",
	"Lava-jato",
	"Lava-louças",
	"Lava",
	"Leão",
	"Leite e biscoitos",
	"Leite",
	"Leitor de mp3",
	"Leitura",
	"Lenço",
	"Lenda de Zelda",
	"Lenhador",
	"lesma",
	"Lesma",
	"Levantamento de peso",
	"Lhama",
	"Libélula",
	"Liderar",
	"Lima",
	"Limão",
	"Limo",
	"Limonada",
	"Limpador de janelas",
	"Língua",
	"Linha de chegada",
	"Linha",
	"Linhas de energia",
	"Liquidificador",
	"Lista Impertinente",
	"Livraria",
	"Livro",
	"Lixo",
	"Lixo",
	"Lixo",
	"Lobisomem",
	"Lobo",
	"Locomotiva a vapor",
	"Logotipo Hypixel",
	"Loja",
	"Londres",
	"Lontra",
	"Lua",
	"Luigi",
	"Lula",
	"Lupa",
	"Luta livre",
	"Lutar",
	"Luvas de boxe",
	"Luvas",
	"Luvas",
	"Luz solar",
	"Luz",
	"Luzes de feriado",
	"Luzes de Natal",
	"Luzes de trânsito",
	"Luzes",
	"Maçã Dourada",
	"Maca",
	"Maçã",
	"Macacão",
	"Macaco",
	"Macaco",
	"Maçaneta",
	"Machado de batalha",
	"Machado",
	"Mãe",
	"Magia",
	"Mágico",
	"Magnético",
	"Mago",
	"Magrelo",
	"Maionese",
	"Mala",
	"Malabarismo",
	"Malabarista",
	"Mamãe",
	"Mamute",
	"Mangueira de jardim",
	"Manhã",
	"Mansão Abandonada",
	"Mansão Abonada",
	"Mansão",
	"Manteiga de amendoim",
	"Manteiga",
	"Mão",
	"Mapa",
	"Máquina de arcade",
	"Máquina de café",
	"Máquina de costura",
	"Máquina de escrever",
	"Máquina de lavar",
	"Maquina de vendas",
	"Máquina do tempo",
	"Máquina",
	"Marca páginas",
	"Marca",
	"Marcador",
	"Mário",
	"Marisco",
	"Mármores",
	"Marshmallow",
	"Marte",
	"Martelo",
	"Máscara de gás",
	"Mascarar",
	"Masmorra",
	"Matemática",
	"Matemática",
	"Mecânico",
	"Medalha de ouro",
	"Medição",
	"Medusa",
	"Meia",
	"Meias",
	"Mel",
	"Melancia",
	"Melão",
	"Mercado",
	"Merendeira",
	"Mergulhando",
	"Mergulho",
	"Mesa de café",
	"Mesa de Computador",
	"Mesa de jantar",
	"Mesa de ping pong",
	"Mesa de sinuca",
	"Mesa de vidro",
	"Mesa",
	"Mesa",
	"Meta",
	"Meteorito",
	"Meu",
	"México",
	"Microfone",
	"Microondas",
	"Mídia social",
	"Milho",
	"Milkshake",
	"Mina de ouro",
	"Minecarrinho",
	"Minecraft",
	"Mineiro",
	"Mineração",
	"Minério",
	"Minhoca",
	"Mini golfe",
	"Míssil",
	"Mobília",
	"Mochila a jato",
	"Mochila",
	"Moeda",
	"Moedas",
	"Moinho de vento",
	"Moldura de imagem",
	"Moldura fotográfica",
	"Molho",
	"Monitor de Computador",
	"Monitor",
	"Monociclo",
	"Monstro de Biscoito",
	"Monstro do lago Ness",
	"Monstros",
	"Montanha russa",
	"Montanha",
	"Morango",
	"Morsa",
	"Morto-vivo",
	"Mostarda",
	"Motocicleta",
	"Motor de bombeiros",
	"Motor",
	"Motosserra",
	"Mouse de computador",
	"Móveis de jardim",
	"Muffin",
	"Mundo",
	"Murchar",
	"Músculo",
	"Museu",
	"Música",
	"Musical",
	"Músico",
	"Nachos",
	"Nadadeira",
	"Namorados",
	"Narciso",
	"Nariz",
	"Nascer do sol",
	"Natação",
	"Natal",
	"Natureza",
	"Naufrágio",
	"Nave espacial",
	"Navegação",
	"Navio afundado",
	"Navio de guerra",
	"Navio pirata",
	"Navio Viking",
	"Negociação",
	"Nervoso",
	"Nevado",
	"Nevando",
	"Nevasca",
	"Neve",
	"Névoa",
	"Ninho de Pássaro",
	"Ninja",
	"Nintendo",
	"Noite",
	"Nota musical",
	"Notas adesivas",
	"Nugget de frango",
	"Nuvens",
	"O fim",
	"O Grinch",
	"O Hulk",
	"Oásis",
	"Obstáculos",
	"Oceano",
	"Ocidental",
	"Octógono",
	"Óculos de segurança",
	"Oculos de sol",
	"Óculos",
	"Oeste selvagem",
	"Oficina do Papai Noel",
	"Oficina do Papai Noel",
	"Oficina",
	"Ogro",
	"Óleo",
	"Olho",
	"Olhos",
	"Olimpíadas",
	"Ombro",
	"Omelete",
	"Ônibus escolar",
	"Ônibus",
	"Orelha",
	"Órgão",
	"Ornamento",
	"Ornitorrinco",
	"Os Simpsons",
	"Osso",
	"Ostra",
	"Ouriço",
	"Ouro",
	"Ouropel",
	"Outono",
	"Ouvidos",
	"Ovelha",
	"Ovo de Dragão",
	"Ovos de pascoa",
	"Ovos",
	"Oxigênio",
	"Pá",
	"Pá",
	"Pacman",
	"Pacote de cartas",
	"Pacote",
	"Pacote",
	"Padaria",
	"Padeiro",
	"Padrão",
	"Pai",
	"Painel publicitário",
	"Painel publicitário",
	"Painel solar",
	"Paintball",
	"Paisagem",
	"Palácio",
	"Paleta de pintura",
	"Paleta",
	"Palhaço",
	"Palito de fósforo",
	"Palmeira",
	"Panda",
	"Panela",
	"Panqueca",
	"Pântano",
	"Pão de alho",
	"Pão",
	"Papagaio",
	"Papai Noel",
	"Papai Noel",
	"Papel de presente",
	"Papel higiênico",
	"Papel",
	"Papoila",
	"Pára-quedas",
	"Parada de mão",
	"Parafuso",
	"Paraíso",
	"Paraquedista",
	"Parede",
	"Parkour",
	"Parque aquático",
	"Parque de diversões",
	"Parque de skate",
	"Parque infantil",
	"Parque temático",
	"Parque",
	"Páscoa",
	"Pássaro",
	"Pássaros",
	"Passeios a cavalo",
	"Passeios em feiras",
	"Pasta de dentes",
	"Pasta",
	"Pastagem",
	"Patas",
	"Patinação",
	"Patinagem no gelo",
	"Patins de gelo",
	"Pátio de construção",
	"Pátio",
	"Pato de borracha",
	"Pato",
	"Pauzinhos",
	"Pavão",
	"Pé de cabra",
	"pé de feijão",
	"Pé Grande",
	"Pé",
	"Peça de xadrez",
	"pedaço de carvão",
	"Pedais",
	"Pedra",
	"Pegada",
	"Peito",
	"Peitoral",
	"Peixe e batata frita",
	"Peixe-espada",
	"Peixe-palhaço",
	"Peixe",
	"Peixinho Dourado",
	"Pelagem",
	"Pelo país",
	"Pena",
	"Pena",
	"Penhasco",
	"Pentágono",
	"Pentear",
	"Pepino",
	"Pera",
	"Perfume",
	"Perna",
	"Pérola",
	"Peru",
	"Peruca",
	"Pés",
	"Pesadelo",
	"Pescador",
	"Pescaria",
	"Pesos",
	"Pêssego",
	"Piano",
	"Picareta",
	"Pico de Gelo",
	"Picolé",
	"Pijamas",
	"Pikachu",
	"Pimenta",
	"Pimenta",
	"Pinata",
	"Pinças",
	"Pincel",
	"Pingue-pongue",
	"Pinguim",
	"Pinha",
	"Pinheiro",
	"Pino de boliche",
	"Pintar",
	"Pintor",
	"Pintura",
	"Pipa",
	"Pipoca",
	"Pirâmide",
	"Pirata",
	"Pirulito",
	"Piscar",
	"Piscina",
	"Piscina",
	"Pista de Boliche",
	"Pista de corrida",
	"Pista de dança",
	"Pista de Hóquei",
	"Pista de Patinação",
	"Pistão",
	"Pistola",
	"Pizza de Abacaxi",
	"Pizza",
	"Placa de Hollywood",
	"Placa de sinalização",
	"Placa",
	"Planeta",
	"Plano",
	"Planta carnívora",
	"Plantar",
	"Plataforma",
	"Plugue",
	"Pneu",
	"Pobre",
	"Poça",
	"Poção",
	"Pode",
	"Pódio",
	"Pokébola",
	"Pokémon",
	"Polícia",
	"Policial",
	"Policial",
	"Polo Norte",
	"Polvo",
	"Pomar",
	"Pombo",
	"Pónei",
	"Pong",
	"Ponte",
	"Ponto de ônibus",
	"Pôr do sol",
	"Porco voador",
	"Porco",
	"Porco",
	"Porta de vidro",
	"Porta lápis",
	"Porta",
	"Portal",
	"Porto",
	"Portões",
	"Poste de iluminação",
	"Poster",
	"Pote de biscoitos",
	"Pote de ouro",
	"Praia",
	"Prancha de mergulho",
	"Prancha de surfe",
	"Prancha",
	"Prateleira",
	"Prato",
	"Pratos",
	"Prédio",
	"Preguiça",
	"Prêmio",
	"Prêmios",
	"Presente",
	"Presente",
	"Presentes",
	"Presunto",
	"Pretzel",
	"Primavera",
	"Primeiro socorro",
	"Princesa",
	"Principe",
	"Prisão",
	"Prisioneiro",
	"Projétil",
	"Protesto",
	"Pudim",
	"Pula-pula",
	"Pular Corda",
	"Pulseira",
	"Pulverizador",
	"Punhal",
	"Punho",
	"Quadra de basquete",
	"Quadra de tênis",
	"Quadrado",
	"Quadricíclo",
	"Quadro branco",
	"Quadro-negro",
	"Quadro",
	"Quarto",
	"Quebra-cabeça",
	"Quebra-cabeça",
	"Quebra-nozes",
	"Quebrado",
	"Queijo suíço",
	"Queijo",
	"Queimada",
	"Queimada",
	"Quicar",
	"Química",
	"Quivi",
	"Rádio",
	"Rainha",
	"Raio",
	"Raposa",
	"Rastejador",
	"Rato",
	"Rato",
	"Ratoeira",
	"Ravina",
	"Reboque",
	"Reciclar",
	"Recife",
	"Rede",
	"Redstone",
	"Refrigerante",
	"Regador",
	"Registro",
	"Rei Kong",
	"Rei",
	"Relâmpago",
	"Relâmpago",
	"Relógio de bolso",
	"Relógio de cuco",
	"Relógio do avô",
	"Relógio",
	"Remo",
	"Remo",
	"Rena",
	"Repolho",
	"Restaurante",
	"Reunião",
	"Revista",
	"Rico",
	"Rindo",
	"Rinoceronte",
	"Rio",
	"Risonho",
	"Robin Hood",
	"Robô",
	"Rock and roll",
	"Roda gigante",
	"Roda",
	"Rodadinha",
	"Rosa",
	"Rosquinha",
	"Rótulo",
	"Rotunda",
	"Rua",
	"Sabão",
	"Sabre de luz",
	"Saco de dormir",
	"Saco de Feijão",
	"Saia",
	"Saída",
	"Sal e pimenta",
	"Sal",
	"Sala de aula",
	"Sala de estar",
	"Sala",
	"Salada de frutas",
	"Salada",
	"Salamandra",
	"Salão",
	"Salmão",
	"Salmoura",
	"Salsicha",
	"Saltando",
	"Salto à vara",
	"Salto alto",
	"Samurai",
	"Sanduíches",
	"Sangramento nasal",
	"Sapato",
	"Sapo de árvore",
	"Sapo",
	"Sapo",
	"Sardinhas",
	"Satélite",
	"Saxofone",
	"Scooby-Doo",
	"Scooter de mobilidade",
	"Secador de cabelo",
	"Seguro",
	"Selim",
	"Selo",
	"Selva",
	"Semente",
	"Sereia",
	"Serra",
	"Seta",
	"Shorts",
	"Show de talentos",
	"Show",
	"Shrek",
	"Silo",
	"Sinal de parada",
	"Sinal",
	"Sinal",
	"Sino",
	"Sistema solar",
	"Skate",
	"SkyWars",
	"Smartphone",
	"Smoking",
	"Snowboard",
	"Sob o mar",
	"Sobrancelha",
	"Sobremesa",
	"Sofá",
	"Sofá",
	"Sol",
	"Soldado de Brinquedo",
	"Soldado",
	"Soletrar",
	"Solo",
	"Som",
	"Sonhar",
	"Sopa",
	"Sorriso",
	"Sorvete de Casquinha",
	"Sorvete",
	"Spleef",
	"Submarino",
	"Suco de laranja",
	"Suco",
	"Suéter",
	"Sumo",
	"Super heroi",
	"Super Mário",
	"Supermercado",
	"Surf",
	"surpresa",
	"Sushi",
	"T-Rex",
	"Taberna",
	"Tabua de passar",
	"Tábua",
	"Tabuleiro de damas",
	"Taco de beisebol",
	"Tambor",
	"Tanque",
	"Tapa-olho",
	"Tapete de rato",
	"Tapete de rato",
	"Tapete mágico",
	"Tapete",
	"Tapete",
	"Tartaruga marinha",
	"Tartaruga",
	"Tartaruga",
	"Tartarugas ninjas",
	"Tatuagem",
	"Táxi",
	"Táxi",
	"Teatro",
	"Tecido",
	"Teclado de computador",
	"Teclado Musical",
	"Tecnologia",
	"Teia de aranha",
	"Teia de aranha",
	"Tela de computador",
	"Tela",
	"Telefone",
	"Telefone",
	"Telescópio",
	"Televisão",
	"Tempestade",
	"Tempo",
	"Têmpora",
	"Tênis de mesa",
	"Tênis",
	"Tênis",
	"Tensão",
	"Termômetro",
	"Terno",
	"Terra",
	"Terras agrícolas",
	"Tesoura",
	"Tesouro",
	"Testa",
	"Teto",
	"Teto",
	"Tetris",
	"Tigela",
	"Tigre",
	"Tijolo",
	"Tingir",
	"Tinta",
	"Tintura para cabelo",
	"Tiro com arco",
	"Tirolesa",
	"Titânico",
	"TNT",
	"Toalha de mesa",
	"Toalha",
	"Toalheiro",
	"Toboágua",
	"Toboágua",
	"Tocha",
	"Tomada",
	"Tomate",
	"Tornado",
	"Torneira",
	"Torradeira",
	"Torre de Pisa",
	"Torre do Relógio",
	"Torre Eiffel",
	"Torre",
	"Torre",
	"Torta de maçã",
	"Torta",
	"Totem Pólo",
	"Touro",
	"Tóxico",
	"Trabalho de casa",
	"Tráfego",
	"Trampolim",
	"Trampolins",
	"Trancar",
	"Transformador",
	"Transporte",
	"Transporte",
	"Transporte",
	"Trapaceando",
	"Trator",
	"Travesseiro",
	"Trem da campanha publicitária",
	"Tremor",
	"Trenó",
	"Trenó",
	"Trens",
	"Trevo-de-quatro-folhas",
	"Triângulo",
	"Triciclo",
	"Tricô",
	"Trigêmeos",
	"Trigo",
	"Trilhos de trem",
	"Triste",
	"Trocar",
	"Troféu",
	"Trolls",
	"Trompete",
	"Trono",
	"Trovão",
	"Trovoada",
	"Truque de mágica",
	"Tsunami",
	"Tubarão",
	"Túnel",
	"Turbina de vento",
	"Unha",
	"Unicórnio",
	"Urso polar",
	"Urso Teddy",
	"Urso",
	"Uvas",
	"Vaca",
	"Vácuo",
	"Vaga-lume",
	"Vagão",
	"Vai andar de kart",
	"Vampiro",
	"Vaninha de Sorvete",
	"Vaqueiro",
	"Varinha mágica",
	"Varinha",
	"Vaso de flores",
	"Vaso de planta",
	"Vaso para plantas",
	"Vaso",
	"Vassoura",
	"Vassoura",
	"Vazamento no telhado",
	"Vegetais",
	"Vegetariano",
	"Veículo",
	"Vela",
	"Velejar",
	"Ventilador de teto",
	"Vento",
	"Verão",
	"Verde",
	"Verruga",
	"Vespa",
	"Vestido formal",
	"Vestir",
	"Via Láctea",
	"Videogame",
	"Videogames",
	"Vidro",
	"Viking",
	"Vila",
	"Vinho",
	"Violino",
	"visco",
	"Vitória Régia",
	"Voar",
	"Volante",
	"Voldemort",
	"Voleibol",
	"Vulcão em erupção",
	"Vulcão",
	"Waffle",
	"Walkie Talkie",
	"Wrecking Ball",
	"X-Burger",
	"Xadrez",
	"Xampu",
	"Xícara de café",
	"Xícara de chá",
	"Xícara",
	"Xilofone",
	"YouTube",
	"Zebra",
	"Zelda",
	"Zeus",
	"Zíper",
	"Zumbi",
]